import { ArrowUpRight, BookOpen, Globe2, ShieldCheck } from 'lucide-react';
import SectionHeading from './SectionHeading';
import { Counter } from './MotionSystem';
import Spotlight from './Spotlight';
import { achievementCounts as count } from '@/data/achievements';
import { profile } from '@/data/profile';
import { projects } from '@/data/projects';

export default function AcademicStats(){return <section id="academic" className="section container section-anchor"><SectionHeading index="02" eyebrow="ACADEMIC EXCELLENCE" title={<>扎实的学业，<span className="subtle">是所有探索的起点。</span></>} description="把知识学深，把所学用到真实的问题里。"/><div className="academic-bento"><Spotlight className="academic-main panel"><div className="card-topline"><span className="micro">WEIGHTED AVERAGE</span><BookOpen size={18}/></div><div className="academic-number"><Counter value={profile.academic.value} decimals={2}/><span>/100</span></div><h3>学年加权平均分</h3><div className="academic-baseline"><span className="tiny-dot"/> 本人提供 · 成绩单与统计学年待补充</div><div className="academic-rules" aria-hidden="true">{Array.from({length:45},(_,i)=><i key={i}/>)}</div></Spotlight><Spotlight className="bento-national panel"><ShieldCheck size={21}/><span className="micro">NATIONAL PLATFORMS</span><h3>CNVD <span> / </span> CNNVD</h3><p>国家级权威网络安全平台技术成果</p><a href="#national" className="bento-link"><span><strong>{count.cnvd+count.cnnvd}</strong> 份证明</span><ArrowUpRight size={19}/></a></Spotlight><Spotlight className="bento-global panel"><Globe2 size={20}/><span className="micro">GLOBAL RECOGNITION</span><div className="bento-big">{count.cve}<span>CVE</span></div><p>国际通用漏洞编号 · 原始记录可查</p><a className="corner-link" href="#global" aria-label="查看国际 CVE 成果"><ArrowUpRight size={19}/></a></Spotlight><Spotlight className="bento-bottom panel"><div><span className="micro">KNOWLEDGE → PRACTICE</span><h3>{count.certifications}<span>项课程与专业认证</span></h3></div><span className="vertical-rule"/><div><span className="micro">IDEA → PRODUCT</span><h3>{projects.length}<span>个可访问的项目</span></h3></div><a href="#projects" className="corner-link" aria-label="查看工程项目"><ArrowUpRight size={18}/></a></Spotlight></div></section>;}
