import AchievementDate from './AchievementDate';
import { ArrowUpRight, Globe2 } from 'lucide-react';
import { cveAchievements } from '@/data/achievements';
import SectionHeading from './SectionHeading';
import Spotlight from './Spotlight';
import { EvidenceButton } from './Exhibition';

function ScoreRing({value}:{value:number}){return <div className={`score-ring ${value<7?'medium-ring':''}`}><svg viewBox="0 0 110 110" aria-hidden="true"><circle cx="55" cy="55" r="47" className="ring-track"/><circle cx="55" cy="55" r="47" className="ring-score" strokeDasharray={`${295.31*value/10} 295.31`}/><circle cx="55" cy="55" r="38" className="ring-inner"/></svg><div><strong>{value.toFixed(1)}</strong><span>CVSS 4.0</span></div></div>;}
export default function CveSection(){return <section id="global" className="section container global-section section-anchor"><div className="split-heading"><SectionHeading index="06" eyebrow="GLOBAL SECURITY RECOGNITION" className="authority-heading" title={<><span className="authority-word">国际</span><span className="authority-title">国际通用漏洞编号成果</span><span className="authority-platforms">CVE</span></>}/><div className="global-explainer" data-reveal><Globe2 size={25}/><h3>CVE · 国际通用漏洞编号</h3><p>全球网络安全行业广泛使用的漏洞唯一编号体系，让安全研究能够被厂商、研究者和漏洞管理系统引用。</p></div></div><div className="cve-grid">{cveAchievements.map((a,i)=><Spotlight key={a.id} className={`panel cve-card ${i<2?'featured-cve':''}`}><div className="card-topline"><span className="micro">CVE RECORD / {a.year}</span><span className={`severity ${a.severity==='HIGH'?'high':'medium'}`}>{a.severity==='HIGH'?'HIGH SEVERITY · 高危':'MEDIUM · 中危'}</span></div><div className="cve-center"><div><h3 id={`detail-${a.id}`} className="achievement-detail">{a.number}</h3><h4>{a.title}</h4><p className="technical-label">{a.technicalTitle}</p></div><ScoreRing value={a.score}/></div><AchievementDate id={a.id}/><p className="achievement-significance">{a.significance}</p><div className="cve-credit"><span>REPORTER</span><strong>Missa <span>(VulDB User)</span></strong></div><div className="cve-links"><EvidenceButton id={a.id} className="text-button">查看证明<ArrowUpRight size={14}/></EvidenceButton><a href={a.evidence.verificationUrl} target="_blank" rel="noopener noreferrer" className="text-button">官方 CVE 记录<ArrowUpRight size={14}/></a></div></Spotlight>)}</div><p className="disclosure">记录与评分已按原始材料核对，统一使用 CVSS 4.0。官方报告人署名为 Missa；荣誉汇总声明为本人。</p></section>;}
