import Image from 'next/image';
import { ArrowUpRight, ArrowRight, FileCheck2, ShieldCheck } from 'lucide-react';
import { nationalAchievements } from '@/data/achievements';
import { evidenceById } from '@/data/evidence';
import { EvidenceButton } from './Exhibition';
import SectionHeading from './SectionHeading';
import Spotlight from './Spotlight';

export default function CybersecuritySection(){return <section id="national" className="section national-section section-anchor"><div className="container"><SectionHeading index="03" eyebrow="NATIONAL CYBERSECURITY RECOGNITION" title={<>国家级权威平台，<br/><span className="serif-accent">记录真实的安全能力。</span></>} description="网络安全的学习，走出课堂之后，是发现问题、严谨验证，并为真实系统的安全作出贡献。"/><div className="national-intro"><p><ShieldCheck size={17}/>国家级权威网络安全技术成果</p><div className="research-flow">{['发现','验证','分析','复现','报告','审核','收录'].map((s,i)=><span key={s}>{s}{i<6&&<ArrowRight size={11}/>}</span>)}</div></div><div className="national-grid"><Spotlight className="national-card cnvd-card panel"><div className="card-topline"><span className="micro">CHINA NATIONAL VULNERABILITY DATABASE</span><span className="tag tag-green">原创漏洞证明</span></div><div className="national-card-content"><div className="national-card-copy"><h3>CNVD<span className="verified-dot"/></h3><h4>国家信息安全漏洞共享平台</h4><p>3 项原创漏洞获平台收录<br/>2 项高危 · 1 项中危</p><div className="issuer-note">证书落款<br/>国家互联网应急中心（CNCERT）等</div><EvidenceButton id="cnvd-20319" className="text-button">查看原创漏洞证明<ArrowUpRight size={16}/></EvidenceButton></div><EvidenceButton id="cnvd-20319" className="certificate-stage portrait" label="高清查看 CNVD 原创漏洞证书"><Image src={evidenceById['cnvd-20319'].thumbnail} width={360} height={505} alt="CNVD 原创漏洞证明完整预览"/><span className="certificate-zoom"><ArrowUpRight size={15}/></span></EvidenceButton></div><div className="meaning"><span><FileCheck2 size={15}/>这意味着什么？</span><p>真实系统中的安全漏洞，经国家级平台审核收录，体现从问题发现到技术报告的完整实践能力。</p></div></Spotlight><Spotlight className="national-card cnnvd-card panel"><div className="card-topline"><span className="micro">NATIONAL VULNERABILITY DATABASE</span><span className="tag">高危</span></div><h3>CNNVD<span className="verified-dot"/></h3><h4>国家信息安全漏洞库</h4><p>中国信息安全测评中心<br/>出具的信息安全漏洞提交证明</p><EvidenceButton id="cnnvd-18260050" className="certificate-stage landscape" label="高清查看 CNNVD 提交证明"><Image src={evidenceById['cnnvd-18260050'].thumbnail} width={510} height={360} alt="CNNVD 信息安全漏洞提交证明完整预览"/><span className="certificate-zoom"><ArrowUpRight size={15}/></span></EvidenceButton><div className="cnnvd-footer"><span className="mono">CNNVD-2026-18260050</span><EvidenceButton id="cnnvd-18260050" className="text-button">查看证明<ArrowUpRight size={16}/></EvidenceButton></div></Spotlight></div><div className="vulnerability-register" data-reveal><div className="register-heading"><span className="micro">THE RESEARCH REGISTER</span><span className="muted">每一个编号，都对应一份原始证明</span></div>{nationalAchievements.map((a)=><EvidenceButton id={a.id} className="register-row" key={a.id}><span className="register-platform">{a.platform}</span><span className="register-title">{a.title}</span><span className="register-id mono">{a.evidence.identifier}</span><span className={`severity ${a.severity==='高危'?'high':'medium'}`}>{a.severity}</span><ArrowUpRight size={17}/></EvidenceButton>)}</div></div></section>;}
