import { ArrowDown, ArrowUpRight, ShieldCheck } from 'lucide-react';
import SecurityCore from './SecurityCore';
import { Counter } from './MotionSystem';
import { profile } from '@/data/profile';
import { achievementCounts } from '@/data/achievements';

export default function Hero(){
 return <section id="home" className="hero section-anchor"><div className="hero-grid"/><div className="hero-inner container"><div className="hero-topline"><span><i className="status-dot"/> DIGITAL HONORS EXHIBITION</span><span>PERSONAL ARCHIVE / 2026</span></div><div className="hero-stage"><div className="hero-copy"><div className="hero-intro"><span className="thin-line"/>以真实成果，回答每一次期待</div><div className="name-lockup"><h1>叶森<span className="name-dot">.</span></h1><span className="romanized">Y E S E N</span></div><h2>以技术回应时代，<br/><span>以实践证明能力。</span></h2><p className="hero-description">从课堂，到真实世界。<br/>这里记录学习的深度、技术的成果，以及实践的答案。</p><div className="hero-actions"><a className="button button-light magnetic" href="#national">探索我的成果<ArrowUpRight size={17}/></a><a className="hero-secondary" href="#archive">查看荣誉档案<ArrowUpRight size={15}/></a></div><div className="hero-disciplines"><span className="desktop-disciplines">CYBERSECURITY<span> / </span>FULL STACK<span> / </span>INNOVATION</span><span className="mobile-disciplines">CNVD<span> / </span>CNNVD<span> / </span>CVE</span></div></div><div className="hero-visual"><SecurityCore/><div className="core-caption"><ShieldCheck size={16}/><span>从发现，到可验证的技术成果</span><span className="micro">EST. 2026</span></div></div></div>
 <div className="hero-metrics"><a href="#academic" className="hero-metric"><span className="metric-number"><Counter value={profile.academic.value} decimals={2}/><small>/ 100</small></span><span className="metric-label">学年加权平均分</span><span className="metric-note">本人提供 · 成绩单待补充</span></a><a href="#edusrc" className="hero-metric"><span className="metric-number"><small className="hash">#</small><Counter value={profile.edusrc.rank}/><span className="metric-tag">EDUSRC</span></span><span className="metric-label">全国月度白帽榜</span><span className="metric-note">2026 年 5 月 · 排名截图存档</span></a><a href="#national" className="hero-metric"><span className="metric-number"><Counter value={achievementCounts.cnvd+achievementCounts.cnnvd+achievementCounts.cve}/><small>项</small><ShieldCheck size={23}/></span><span className="metric-label">国内外安全成果记录</span><span className="metric-note">CNVD {achievementCounts.cnvd} · CNNVD {achievementCounts.cnnvd} · CVE {achievementCounts.cve}</span></a><a href="#social" className="hero-metric"><span className="metric-number"><Counter value={profile.volunteer.value}/><small>h</small></span><span className="metric-label">志愿服务时长</span><span className="metric-note">本人提供 · 时长证明待补充</span></a></div><div className="hero-bottom"><span>学习有深度，成果有依据。</span><a href="#academic">SCROLL TO EXPLORE <ArrowDown size={13}/></a><span>01 — 12</span></div></div></section>;
}
